### ISSUE TITLE
Finer sign/keyword highlighting control

### ISSUE THREAD

**Issue by shammellee** [gumpu/ROBODoc#11]
Currently, all signs and keywords use the same css classes `span.sign` and `span.keyword`, respectively. I'd like to have finer control to give code elements more specific styling.

A possible solution could be to specify the class to use for a specific code element in the config file…

```
# robodoc.rc

# syntax: <element(s)> <css_classname>
signs:
  {} sign_braces
  () sign_parens
  =  sign_assignment

# syntax: <keyword(s)> <css_classname>
keywords:
  new               keyword_new
  return            keyword_return
  if, elseif, else  keyword_conditional
  try, catch, throw keyword_exception
```

We could then customize those css classes…

``` css
/* stylesheet */
span.sign_braces{color:red}
span.sign_parens{color:blue}
span.sign_assignment{color:#FF00FF}

span.keyword_new{color:#00FFFF}
span.keyword_return{green}
span.keyword_conditional{color:yellow}
span.keyword_exception{color:red}
```
